// Import the createSlice function from Redux Toolkit, which is used to create a slice of the state.
import { createSlice } from '@reduxjs/toolkit';

// Define and export the authSlice using the createSlice function.
export const authSlice = createSlice({
  name: 'auth', // Name of the slice, used in action types.
  initialState: {
    user: null, // Initial state for the user, starting as null indicating no user is logged in.
    token: null, // Initial state for the token, starting as null indicating no authentication token is present.
  },
  reducers: {
    // Reducer for setting user credentials upon login.
    setCredentials: (state, action) => {
      // Reducer for setting user credentials upon login.
      state.user = action.payload.user;
      state.token = action.payload.token;
    },
    // Reducer for handling user logout.
    logout: (state) => {
      // Reset the user and token to null, effectively logging the user out.
      state.user = null;
      state.token = null;
    },
    // Reducer for updating the user's profile.
    updateProfile: (state, action) => {
      // Update the user state with the new profile details, merging them with existing user details.
      state.user = { ...state.user, ...action.payload };
    },
  },
});

// Export the actions generated by the slice, to be used in the application to dispatch these actions.
export const { setCredentials, logout, updateProfile } = authSlice.actions;

// Export the reducer function of the auth slice, to be included in the store.
export default authSlice.reducer;
